import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Aside from "./components/Aside";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="bg-gray-100 min-h-screen">
          <main className="container mx-auto max-w-screen-xl p-6 pt-24 lg:flex lg:space-x-6">
            <Aside/>
            {children}
          </main>
        </div>
        <footer>
          푸터
        </footer>
      </body>
    </html>
  );
}
