"use client"
import { Session } from "next-auth";

import type { Metadata } from "next";
// import { SessionProvider } from "next-auth/react";
// import { QueryClientProvider } from '@tanstack/react-query';
import "./globals.css";
import Header from "./components/Header";
// import Aside from "./components/Aside";
import { getQueryClient } from "./utils/queryHelpers";
import dynamic from "next/dynamic";
// const inter = Inter({ subsets: ["latin"] });
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// 동적으로 클라이언트 컴포넌트를 불러옴
const Aside = dynamic(() => import("./components/Aside"), { ssr: false });
const SessionProvider = dynamic(() => import("next-auth/react").then(mod => mod.SessionProvider), { ssr: false });
const QueryClientProvider = dynamic(() => import('@tanstack/react-query').then(mod => mod.QueryClientProvider), { ssr: false });

const queryClient = getQueryClient();

interface LayoutProps {
  children: React.ReactNode;
  session?: Session | null;  // 'session'을 명시적으로 정의
}

export default function RootLayout({
  children,
  session
}: 
  LayoutProps
) {

  return (
    <html lang="en">
        <body>
          <Header />
          <div className="bg-gray-100 min-h-screen">
            <main className="container mx-auto max-w-screen-xl p-6 pt-24 lg:flex lg:space-x-6">
              <QueryClientProvider client={queryClient}>
                <SessionProvider session={session}>
                  <Aside/>
                  {children}
                </SessionProvider>
              </QueryClientProvider>
            </main>
          </div>

          <div className="my-4 border-t border-gray-200"></div>

          {/* <footer className="bg-gray-500 h-4">
            푸터
          </footer> */}
        </body>
      </html>
  );
}
